{% set name = "moka-py" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moka_py-{{ version }}.tar.gz
  sha256: 038b4aa7fdeaafba80d7aacff0fa637ffa42626efc19aed1bf13915ad1cf4a04

build:
  skip: true  # [py<39]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.7,<2.0
    - pip
  run:
    - python

test:
  imports:
    - moka_py
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deliro/moka-py
  summary: A high performance caching library for Python written in Rust.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
